#!/usr/bin/env sh
#
# Fails when a fingerprint that reads as machine-written appears in the repo:
# an em dash, or an AI-attribution trailer or footer. The repo bans both in
# source, docs, and commit messages. Use commas, parentheses, or colons in
# place of an em dash, and write every commit as the engineer who owns it.
#
# Pass a git range as the first argument to also scan commit messages, for
# example: sh scripts/check-fingerprints.sh origin/main..HEAD

set -eu

dash=$(printf '\342\200\224')
attribution='co-authored-by:[[:space:]]*(claude|anthropic)|generated with \[?claude|generated by claude|ai-generated|ai-assisted'

# These files name the patterns they search for, so they are excluded from the
# scan to avoid matching themselves.
self="scripts/check-fingerprints.sh"
workflow=".github/workflows/ci.yml"
hook=".husky/commit-msg"
fail=0

if git grep -nI "$dash" -- ":!package-lock.json" ":!$self" ":!$workflow" ":!$hook"; then
  echo "Found an em dash above. Use a comma, parentheses, a colon, or rewrite."
  fail=1
fi

if git grep -nIiE "$attribution" -- ":!$self" ":!$workflow" ":!$hook"; then
  echo "Found AI attribution above. Every commit and doc reads as its owner."
  fail=1
fi

range="${1:-}"
if [ -n "$range" ]; then
  if git log --format='%B' "$range" | grep -nIiE "$attribution"; then
    echo "Found AI attribution in a commit message in range $range."
    fail=1
  fi
  if git log --format='%B' "$range" | grep -nI "$dash"; then
    echo "Found an em dash in a commit message in range $range."
    fail=1
  fi
fi

if [ "$fail" -ne 0 ]; then
  exit 1
fi

echo "No fingerprints found."
